name: 'Git Automatic Semantic Versioning'
description: 'Automatically create new semantci version string based on commit message'
author: 'Bitshift'
outputs:
  version-string:
    description: 'Semantic version string'
runs:
  using: 'docker'
  image: 'Dockerfile'
