name: 'Git Automatic Semantic Versioning'
description: 'Automatically create new semantci version string based on commit message'
author: 'Bitshift'
inputs:
  main_branch:
    description: 'Main branch for the repository'
    required: false
    default: 'main'
  initial_version:
    description: 'First version, defaults to 1.0.0'
    required: false
    default: '1.0.0'
  create_tag:
    description: 'Automatically create tag in repository'
    required: false
    default: 'false'
  tag_prefix:
    description: 'Tag prefix, if tag creation is enabled. Tag will be named `prefix<version>`. Defaults to `v`'
    required: false
    default: 'v'
  manual_bump:
    description: 'Manual bump type, can be `patch`, `minor`, `major`. If empty (default), the script will determine the bump type based on commit messages.'
    required: false
    default: ''
outputs:
  version-string:
    description: 'Semantic version string'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: blue
  icon: tag
