name: 'Git Automatic Semantic Versioning'
description: 'Automatically create new semantci version string based on commit message'
author: 'Bitshift'
inputs:
  main_branch:
    description: 'Main branch for the repository'
    required: false
    default: 'main'
  initial_version:
    description: 'First version, defaults to 1.0.0'
    required: false
    default: '1.0.0'
outputs:
  version-string:
    description: 'Semantic version string'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: blue
  icon: tag
